In [1]:
using CairoMakie, LaTeXStrings
using Makie.Colors

In [2]:
include("./myfuncs.jl")
using .MyFuncs

In [15]:
using Graphs
adjacency_matrix(NWnetworks(10, 0.2)) * [1:10...]

10-element Vector{Int64}:
 12
  4
 11
  8
 23
 12
 14
 16
 18
 15

In [14]:
[neighbors(NWnetworks(10, 0.2),i) for i in 1:10]

10-element Vector{Vector{Int64}}:
 [2, 10]
 [1, 3]
 [2, 4, 5]
 [3, 5]
 [3, 4, 6, 10]
 [5, 7]
 [6, 8]
 [7, 9]
 [8, 10]
 [1, 5, 9]

In [4]:
NWnetworks(10,0.01)

{10, 10} undirected simple Int64 graph

In [7]:
tHH = HH{Float64}(N=1000, p =0.001)

HH{Float64}(Main.MyFuncs.HHPara{Float64}(1.0, 120.0, 36.0, 0.3, 50.0, -72.0, -49.0, -20.0, 20.0, 0.5, 8.0, 2.0, 0.125), 0.001, 0x03e8, [-61.77, -61.77, -61.77, -61.77, -61.77, -61.77, -61.77, -61.77, -61.77, -61.77  …  -61.77, -61.77, -61.77, -61.77, -61.77, -61.77, -61.77, -61.77, -61.77, -61.77], [0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08  …  0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08], [0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48  …  0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48], [0.36, 0.36, 0.36, 0.36, 0.36, 0.36, 0.36, 0.36, 0.36, 0.36  …  0.36, 0.36, 0.36, 0.36, 0.36, 0.36, 0.36, 0.36, 0.36, 0.36], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], Graphs.SimpleGraphs.SimpleGraph{Int64}(1002, [[2, 1000], [1, 3], [2, 4], [3, 5], [4, 6], [5, 7], [6, 8], [7, 9], [8, 10], [9, 11]  …  [990, 992], [991, 993], [992, 994], [993, 995], [994, 996], [995, 997], [996, 998], [9

In [10]:
tHH.r[tHH.neighbors[1]]

2-element Vector{Float64}:
 0.0
 0.0

In [4]:
tg = NWnetworks(1000, 0.001)

{1000, 1002} undirected simple Int64 graph

In [9]:
using Graphs

In [11]:
[ neighbors(tg,i) for i in 1:1000]

1000-element Vector{Vector{Int64}}:
 [2, 1000]
 [1, 3]
 [2, 4]
 [3, 5]
 [4, 6]
 [5, 7]
 [6, 8]
 [7, 9]
 [8, 10]
 [9, 11]
 ⋮
 [991, 993]
 [992, 994]
 [993, 995]
 [994, 996]
 [995, 997]
 [996, 998]
 [997, 999]
 [998, 1000]
 [1, 999]

In [54]:
single_HH = HH{Float64}(N=1)
T = 200
dt = 0.001

for j in 1:100000
    update!(single_HH, single_HH.param, 0 * ones(1), dt)
end
Vs = Vector{Vector{Float64}}(undef, length([0:dt:T...]))
# spike_times = rand([1000:10000...],100)
for (i, Ie) in enumerate(genIexs(1,2;dt=0.001, iInterval=0.001, T=T))
    update!(single_HH, single_HH.param, 20 .* Ie, dt)
    Vs[i] = single_HH.v[:]
end

In [55]:
sum((vcat(Vs...)[1:end-1] .<0) .& (vcat(Vs...)[2:end] .> 0))

58

In [ ]:
[ for i in 0:0]

In [176]:
nframes = 60
framerate = 10
Iext_iterator = -5:1:12

-5:1:12

In [25]:
fig = Figure()
ax = Axis(fig[1, 1])
lines!(ax, [0:dt:T...], vcat(Vs...); linewidth=1.5, color=:gray)
ylims!(ax, (-100, 50))
fig

UndefVarError: UndefVarError: `Vs` not defined

In [ ]:
NWnetworks(1000, 0.001)

In [24]:
dt = 0.001;
T = 50;

framerate = 10;
Iext_iterator = -5:1:12;

single_HH = HH{Float64}(N=1, p = 0.1)
fig = Figure()
ax = Axis(fig[1, 1])

record(fig, "t.gif", Iext_iterator;
        framerate = framerate) do iex
    Vs = Vector{Vector{Float64}}(undef, length([0:dt:T...]))
    for j in 1:1e5
        update!(single_HH, single_HH.param, -5 * ones(1), dt)
    end

    for i in 1:length([0:dt:T...])
        update!(single_HH, single_HH.param, iex * ones(1), dt)
        Vs[i] = single_HH.v[:]
    end
    empty!(ax)
    # ax.names.title="10"
    lines!(ax, [0:dt:50...], vcat(Vs...); linewidth=1.5, color=:gray)
    lines!(ax, [0,50], zeros(2); linewidth=1, color=:black, linestyle=:dash)
    text!(ax,latexstring(L"I_{\text{ex}} =" * string(iex) * L"\,\mathrm{nA}"), position=(25, 45), align = (:center, :center))
    ylims!(ax, (-75, 50))
    xlims!(ax, (0,50))
    ax.xlabel = "Time (ms)"
    ax.ylabel = "Membrane potential (mV)"
    hidedecorations!(ax, ticklabels=false, label=false)
end

"t.gif"